[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 日志
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %H:%M:%S

# 报告
addopts = -v --tb=short

# 环境默认
env = dev
